# Generated by Django 5.1.2 on 2024-11-02 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('start_location_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_location_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Active'), (2, 'Completed'), (3, 'Cancelled')], default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_message', models.CharField(max_length=255)),
                ('withdraw_message', models.CharField(blank=True, max_length=255)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected'), (3, 'Withdrawn')], default=0)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journey.journey')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('meeting_time', models.DateTimeField()),
                ('meeting_location_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('meeting_location_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.IntegerField(choices=[(0, 'Proposed'), (1, 'Accepted'), (2, 'Rejected')], default=0)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journey.journey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journey.request')),
            ],
            options={
                'ordering': ['-status'],
            },
        ),
    ]
