# Generated by Django 5.1.2 on 2024-11-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0003_alter_journey_creator_alter_meeting_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_time',
            field=models.TimeField(),
        ),
    ]
