# Generated by Django 5.1.2 on 2024-11-03 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0004_alter_meeting_meeting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journey.request'),
        ),
    ]
