# Generated by Django 5.1.2 on 2024-11-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0005_alter_meeting_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='withdraw_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
